# HTTP Server.
server:
  domain: "http://127.0.0.1:8299"
  address: ":8299"
  serverRoot: "resource/public"
  openapiPath: "/openApi.json"
  swaggerPath: "/doc"
  DumpRouterMap: false
  logPath: "./runtime/log/server"
  ErrorStack: true                      # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
  ErrorLogEnabled: true                      # 是否记录异常日志信息到日志中。默认为true
  errorLogPattern: "error/{Y-m-d}.log"       # 异常错误日志文件格式。默认为"error-{Ymd}.log"
  accessLogEnabled: true                      # 是否记录访问日志。默认为false
  accessLogPattern: "access/{Y-m-d}.log"      # 访问日志文件格式。默认为"access-{Ymd}.log"


# Global logging.
logger:
  level: "all"
  stdout: true
  headerPrint: false
  ctxKeys: [ ]
  path: "./runtime/log/logger"            # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file: "{Y-m-d}.log"                     # 日志文件格式。默认为"{Y-m-d}.log"
  exception: # 系统异常日志
    path: "./runtime/log/exception"
    level: "all"
    file: "{Y-m-d}.log"
  queue: # 消息队列日志
    path: "./runtime/log/queue"
    level: "all"
    file: "{Y-m-d}.log"


#JWT
jwt:
  version: "1.0"                       # 版本号
  expires: "864000"                     # 有效期，单位：秒
  sign: "xxx"                     # 秘钥，考虑安全问题请修改默认值
  multiPort: true                        # 是否允许多端登录，默认为true

#JWT
jwtmall:
  version: "1.0"                       # 版本号
  expires: "864000000"                     # 有效期，单位：秒
  sign: "xxx"                     # 秘钥，考虑安全问题请修改默认值
  multiPort: true                        # 是否允许多端登录，默认为true


# Redis数据库配置
redis:
  default:
    address: "127.0.0.1:6379"
    db: "1"
    pass: ""
    idleTimeout: "20"


# Database.
database:
  logger:
    level: "all"
    stdout: false

  default:
    link: "mysql:root:your_pwd@tcp(127.0.0.1:3306)/your_db"
    debug: true
    Prefix: ""


# CLI.
gfcli:
  build:
    name: "xxx"
  gen:
    dao:
      - link: "mysql:root:your_pwd@tcp(127.0.0.1:3306)/your_db"
        #        tables:          "" #指定当前数据库中需要执行代码生成的数据表。如果为空，表示数据库的所有表都会生成。
        #        tablesEx:        "" #指定当前数据库中需要排除代码生成的数据表。
        removePrefix: ""
        descriptionTag: true
        noModelComment: true
        path: "./app"
        daoPath: "dao"
        doPath: "model/do"
        jsonCase: "Snake"

