// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleTagRelations is the golang structure of table article_tag_relations for DAO operations like Where/Data.
type ArticleTagRelations struct {
	g.Meta     `orm:"table:article_tag_relations, do:true"`
	ArticleId  interface{} // 文章id
	TagId      interface{} // 标签id
	CreateTime *gtime.Time // 创建时间
}
