// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogArticles is the golang structure of table blog_articles for DAO operations like Where/Data.
type BlogArticles struct {
	g.Meta     `orm:"table:blog_articles, do:true"`
	Id         interface{} //
	Title      interface{} // 标题
	Content    interface{} // 内容
	TagId      interface{} // 标签id
	UserId     interface{} // 用户id
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
}
