// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogUsers is the golang structure of table blog_users for DAO operations like Where/Data.
type BlogUsers struct {
	g.Meta     `orm:"table:blog_users, do:true"`
	Id         interface{} // 用户id
	Username   interface{} // 用户名
	Password   interface{} // 密码
	Salt       interface{} // 密码盐
	Email      interface{} // 邮箱
	Phone      interface{} // 手机号
	IsBanned   interface{} // 1封禁0未封禁
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 修改时间
	LastIp     interface{} // 最后一次登录的ip
}
