// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserArticleRelations is the golang structure of table user_article_relations for DAO operations like Where/Data.
type UserArticleRelations struct {
	g.Meta     `orm:"table:user_article_relations, do:true"`
	UserId     interface{} // 用户id
	ArticleId  interface{} // 文章id
	CreateTime *gtime.Time // 创建时间
}
