// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BlogTagsDao is the data access object for table blog_tags.
type BlogTagsDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns BlogTagsColumns // columns contains all the column names of Table for convenient usage.
}

// BlogTagsColumns defines and stores column names for table blog_tags.
type BlogTagsColumns struct {
	Id         string // 标签id
	Name       string // 标签名
	CreateTime string // 创建时间
}

// blogTagsColumns holds the columns for table blog_tags.
var blogTagsColumns = BlogTagsColumns{
	Id:         "id",
	Name:       "name",
	CreateTime: "create_time",
}

// NewBlogTagsDao creates and returns a new DAO object for table data access.
func NewBlogTagsDao() *BlogTagsDao {
	return &BlogTagsDao{
		group:   "default",
		table:   "blog_tags",
		columns: blogTagsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BlogTagsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BlogTagsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BlogTagsDao) Columns() BlogTagsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BlogTagsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BlogTagsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BlogTagsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
