// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BlogUsersDao is the data access object for table blog_users.
type BlogUsersDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns BlogUsersColumns // columns contains all the column names of Table for convenient usage.
}

// BlogUsersColumns defines and stores column names for table blog_users.
type BlogUsersColumns struct {
	Id         string // 用户id
	Username   string // 用户名
	Password   string // 密码
	Salt       string // 密码盐
	Email      string // 邮箱
	Phone      string // 手机号
	IsBanned   string // 1封禁0未封禁
	CreateTime string // 创建时间
	UpdateTime string // 修改时间
	LastIp     string // 最后一次登录的ip
}

// blogUsersColumns holds the columns for table blog_users.
var blogUsersColumns = BlogUsersColumns{
	Id:         "id",
	Username:   "username",
	Password:   "password",
	Salt:       "salt",
	Email:      "email",
	Phone:      "phone",
	IsBanned:   "is_banned",
	CreateTime: "create_time",
	UpdateTime: "update_time",
	LastIp:     "last_ip",
}

// NewBlogUsersDao creates and returns a new DAO object for table data access.
func NewBlogUsersDao() *BlogUsersDao {
	return &BlogUsersDao{
		group:   "default",
		table:   "blog_users",
		columns: blogUsersColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BlogUsersDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BlogUsersDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BlogUsersDao) Columns() BlogUsersColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BlogUsersDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BlogUsersDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BlogUsersDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
