// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserArticleRelationsDao is the data access object for table user_article_relations.
type UserArticleRelationsDao struct {
	table   string                      // table is the underlying table name of the DAO.
	group   string                      // group is the database configuration group name of current DAO.
	columns UserArticleRelationsColumns // columns contains all the column names of Table for convenient usage.
}

// UserArticleRelationsColumns defines and stores column names for table user_article_relations.
type UserArticleRelationsColumns struct {
	UserId     string // 用户id
	ArticleId  string // 文章id
	CreateTime string // 创建时间
}

// userArticleRelationsColumns holds the columns for table user_article_relations.
var userArticleRelationsColumns = UserArticleRelationsColumns{
	UserId:     "user_id",
	ArticleId:  "article_id",
	CreateTime: "create_time",
}

// NewUserArticleRelationsDao creates and returns a new DAO object for table data access.
func NewUserArticleRelationsDao() *UserArticleRelationsDao {
	return &UserArticleRelationsDao{
		group:   "default",
		table:   "user_article_relations",
		columns: userArticleRelationsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserArticleRelationsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserArticleRelationsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserArticleRelationsDao) Columns() UserArticleRelationsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserArticleRelationsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserArticleRelationsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserArticleRelationsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
