// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"yx-blog/internal/dao/internal"
)

// internalArticleTagRelationsDao is internal type for wrapping internal DAO implements.
type internalArticleTagRelationsDao = *internal.ArticleTagRelationsDao

// articleTagRelationsDao is the data access object for table article_tag_relations.
// You can define custom methods on it to extend its functionality as you wish.
type articleTagRelationsDao struct {
	internalArticleTagRelationsDao
}

var (
	// ArticleTagRelations is globally public accessible object for table article_tag_relations operations.
	ArticleTagRelations = articleTagRelationsDao{
		internal.NewArticleTagRelationsDao(),
	}
)

// Fill with you ideas below.
