// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"yx-blog/internal/dao/internal"
)

// internalBlogUsersDao is internal type for wrapping internal DAO implements.
type internalBlogUsersDao = *internal.BlogUsersDao

// blogUsersDao is the data access object for table blog_users.
// You can define custom methods on it to extend its functionality as you wish.
type blogUsersDao struct {
	internalBlogUsersDao
}

var (
	// BlogUsers is globally public accessible object for table blog_users operations.
	BlogUsers = blogUsersDao{
		internal.NewBlogUsersDao(),
	}
)

// Fill with you ideas below.
