// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"yx-blog/internal/dao/internal"
)

// internalBlogTagsDao is internal type for wrapping internal DAO implements.
type internalBlogTagsDao = *internal.BlogTagsDao

// blogTagsDao is the data access object for table blog_tags.
// You can define custom methods on it to extend its functionality as you wish.
type blogTagsDao struct {
	internalBlogTagsDao
}

var (
	// BlogTags is globally public accessible object for table blog_tags operations.
	BlogTags = blogTagsDao{
		internal.NewBlogTagsDao(),
	}
)

// Fill with you ideas below.
