// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"yx-blog/internal/dao/internal"
)

// internalBlogArticlesDao is internal type for wrapping internal DAO implements.
type internalBlogArticlesDao = *internal.BlogArticlesDao

// blogArticlesDao is the data access object for table blog_articles.
// You can define custom methods on it to extend its functionality as you wish.
type blogArticlesDao struct {
	internalBlogArticlesDao
}

var (
	// BlogArticles is globally public accessible object for table blog_articles operations.
	BlogArticles = blogArticlesDao{
		internal.NewBlogArticlesDao(),
	}
)

// Fill with you ideas below.
