// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"yx-blog/internal/dao/internal"
)

// internalUserArticleRelationsDao is internal type for wrapping internal DAO implements.
type internalUserArticleRelationsDao = *internal.UserArticleRelationsDao

// userArticleRelationsDao is the data access object for table user_article_relations.
// You can define custom methods on it to extend its functionality as you wish.
type userArticleRelationsDao struct {
	internalUserArticleRelationsDao
}

var (
	// UserArticleRelations is globally public accessible object for table user_article_relations operations.
	UserArticleRelations = userArticleRelationsDao{
		internal.NewUserArticleRelationsDao(),
	}
)

// Fill with you ideas below.
