// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleTagRelations is the golang structure for table article_tag_relations.
type ArticleTagRelations struct {
	ArticleId  int         `json:"articleId"  ` // 文章id
	TagId      int         `json:"tagId"      ` // 标签id
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
}
