// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogUsers is the golang structure for table blog_users.
type BlogUsers struct {
	Id         int         `json:"id"         ` // 用户id
	Username   string      `json:"username"   ` // 用户名
	Password   string      `json:"password"   ` // 密码
	Salt       string      `json:"salt"       ` // 密码盐
	Email      string      `json:"email"      ` // 邮箱
	Phone      string      `json:"phone"      ` // 手机号
	IsBanned   int         `json:"isBanned"   ` // 1封禁0未封禁
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 修改时间
	LastIp     string      `json:"lastIp"     ` // 最后一次登录的ip
}
