// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogArticles is the golang structure for table blog_articles.
type BlogArticles struct {
	Id         int         `json:"id"         ` //
	Title      string      `json:"title"      ` // 标题
	Content    string      `json:"content"    ` // 内容
	TagId      int         `json:"tagId"      ` // 标签id
	UserId     int         `json:"userId"     ` // 用户id
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
}
