// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogTags is the golang structure for table blog_tags.
type BlogTags struct {
	Id         int         `json:"id"         ` // 标签id
	Name       string      `json:"name"       ` // 标签名
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
}
