// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserArticleRelations is the golang structure for table user_article_relations.
type UserArticleRelations struct {
	UserId     int         `json:"userId"     ` // 用户id
	ArticleId  int         `json:"articleId"  ` // 文章id
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
}
